_target_: lightning.pytorch.trainer.Trainer

# optimizer, trainer
# future discount, trainer
# vis interval, trainer
default_root_dir: ${paths.output_dir}


min_epochs: 1 # prevents early stopping
max_epochs: 500

sync_batchnorm: True

fast_dev_run: False
overfit_batches: 0

num_sanity_val_steps: 1
val_check_interval: null

log_every_n_steps: 25

limit_train_batches: null
limit_val_batches: null
accumulate_grad_batches: 8

accelerator: cpu
devices: 1

# 16 bit precision or 32 bit
precision: 32

gradient_clip_val: 5

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
