_target_: src.trainer.trainer.BevLightingModule

model:
  # _target_: src.models.damp.Damp
  bn_momentum: 0.1
  instance_flow_enabled: False
  
  encoder:
    out_channels: 64
    use_depth_distribution: True
    downsample: 8
    name: efficientnet-b0

  image:
    final_dim: [224, 480]
    resize_scale: 0.3
    top_crop: 46
    original_height: 900
    original_width: 1600
    names: [CAM_FRONT_LEFT, CAM_FRONT, CAM_FRONT_RIGHT, CAM_BACK_LEFT, CAM_BACK, CAM_BACK_RIGHT]

  temporal_model:
    name: 'temporal_block'  # type of temporal model
    start_out_channels: 64
    extra_in_channels: 0
    inbetween_layers: 0
    use_pyramid_pooling: True
    input_egopose: True



