
_target_: src.models.damp.Damp

# compile model for faster training with pytorch 2.0
compile: false
receptive_field: 3  # how many frames of temporal context (1 for single timeframe)
bn_momentum: 0.1

receptive_field: 3

encoder:
  _target_: src.models.components.encoder.Encoder
  _partial_: true
  out_channels: 64
  use_depth_distribution: true
  downsample: 8
  name: efficientnet-b0

image:
  final_dim: [224, 480]
  resize_scale: 0.3
  top_crop: 46
  original_height: 900
  original_width: 1600
  names: [CAM_FRONT_LEFT, CAM_FRONT, CAM_FRONT_RIGHT, CAM_BACK_LEFT, CAM_BACK, CAM_BACK_RIGHT]

temporal_model:
  name: 'temporal_block'  # type of temporal model
  start_out_channels: 64
  extra_in_channels: 0
  inbetween_layers: 0
  pyramid_pooling: true
  input_egopose: true

