# @package _global_

defaults:
  - _self_
  - common: damp
  - data: data
  - model: damp
  - logger: tensorboard
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "./last.ckpt"
